version: "3.9"

services:
  commerce-db:
    image: postgres:16
    container_name: commerce-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: commerce
    volumes:
      - commerce_data:/var/lib/postgresql/data

  profile-db:
    image: postgres:16
    container_name: profile-db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: profile
    volumes:
      - profile_data:/var/lib/postgresql/data

  payment-db:
    image: postgres:16
    container_name: payment-db
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: payment
    volumes:
      - payment_data:/var/lib/postgresql/data

volumes:
  commerce_data:
  profile_data:
  payment_data:
